/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author lxn
 */
public class JDlgMmsProduto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgMmsProduto.class.getName());

    /**
     * Creates new form JDlgMmsProduto
     */
    public JDlgMmsProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Produto");
        setLocationRelativeTo(null);
        jTxtMmsCategoria.setEnabled(false);
        jTxtMmsCodigo.setEnabled(false);
        jTxtMmsDescricao.setEnabled(false);
        jTxtMmsFornecedor.setEnabled(false);
        jTxtMmsIQuantidade.setEnabled(false);
        jTxtMmsMarca.setEnabled(false);
        jTxtMmsPreco.setEnabled(false);
        jTxtMmsProduto.setEnabled(false);
        jBtnMmsCancelar.setEnabled(false);
        jBtnMmsConfirmar.setEnabled(false);
        jBtnMmsIncluir.setEnabled(true);
        jBtnMmsExcluir.setEnabled(true);
        jBtnMmsPesquisar.setEnabled(true);
        jBtnMmsAlterar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnMmsIncluir = new javax.swing.JButton();
        jBtnMmsAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtMmsCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtMmsDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnMmsExcluir = new javax.swing.JButton();
        jTxtMmsCategoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtMmsPreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtMmsIQuantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtMmsFornecedor = new javax.swing.JTextField();
        jBtnMmsConfirmar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtMmsMarca = new javax.swing.JTextField();
        jBtnMmsCancelar = new javax.swing.JButton();
        jBtnMmsPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtMmsProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnMmsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/incluir.png"))); // NOI18N
        jBtnMmsIncluir.setText("Incluir");
        jBtnMmsIncluir.addActionListener(this::jBtnMmsIncluirActionPerformed);

        jBtnMmsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/alterar.png"))); // NOI18N
        jBtnMmsAlterar.setText("Alterar");
        jBtnMmsAlterar.addActionListener(this::jBtnMmsAlterarActionPerformed);

        jLabel2.setText("Código:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Categoria:");

        jBtnMmsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/Excluir.png"))); // NOI18N
        jBtnMmsExcluir.setText("Excluir");
        jBtnMmsExcluir.addActionListener(this::jBtnMmsExcluirActionPerformed);

        jLabel5.setText("Preço:");

        jLabel6.setText("Quantidade no estoque:");

        jLabel7.setText("Fornecedor:");

        jBtnMmsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/confirmar.png"))); // NOI18N
        jBtnMmsConfirmar.setText("Confirmar");
        jBtnMmsConfirmar.addActionListener(this::jBtnMmsConfirmarActionPerformed);

        jLabel8.setText("Marca:");

        jBtnMmsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cancelar.png"))); // NOI18N
        jBtnMmsCancelar.setText("Cancelar");
        jBtnMmsCancelar.addActionListener(this::jBtnMmsCancelarActionPerformed);

        jBtnMmsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/pesquisar.png"))); // NOI18N
        jBtnMmsPesquisar.setText("Pesquisar");

        jLabel1.setText("Produto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMmsPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtMmsIQuantidade)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTxtMmsFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTxtMmsMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMmsProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMmsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtMmsDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtMmsCategoria)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnMmsIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMmsAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMmsExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMmsConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMmsCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMmsPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMmsProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMmsPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsIQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnMmsExcluir)
                        .addComponent(jBtnMmsConfirmar)
                        .addComponent(jBtnMmsCancelar)
                        .addComponent(jBtnMmsPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnMmsIncluir)
                        .addComponent(jBtnMmsAlterar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMmsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsIncluirActionPerformed
        // TODO add your handling code here:
        jTxtMmsCategoria.setEnabled(true);
jTxtMmsCodigo.setEnabled(true);
jTxtMmsDescricao.setEnabled(true);
jTxtMmsFornecedor.setEnabled(true);
jTxtMmsIQuantidade.setEnabled(true);
jTxtMmsMarca.setEnabled(true);
jTxtMmsPreco.setEnabled(true);
jTxtMmsProduto.setEnabled(true);
jBtnMmsCancelar.setEnabled(true);
jBtnMmsConfirmar.setEnabled(true);
jBtnMmsIncluir.setEnabled(false);
jBtnMmsExcluir.setEnabled(false);
jBtnMmsPesquisar.setEnabled(false);
jBtnMmsAlterar.setEnabled(false);
    }//GEN-LAST:event_jBtnMmsIncluirActionPerformed

    private void jBtnMmsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsConfirmarActionPerformed
        // TODO add your handling code here:
        jTxtMmsCategoria.setEnabled(true);
jTxtMmsCodigo.setEnabled(true);
jTxtMmsDescricao.setEnabled(true);
jTxtMmsFornecedor.setEnabled(true);
jTxtMmsIQuantidade.setEnabled(true);
jTxtMmsMarca.setEnabled(true);
jTxtMmsPreco.setEnabled(true);
jTxtMmsProduto.setEnabled(true);
jBtnMmsCancelar.setEnabled(true);
jBtnMmsConfirmar.setEnabled(true);
jBtnMmsIncluir.setEnabled(false);
jBtnMmsExcluir.setEnabled(false);
jBtnMmsPesquisar.setEnabled(false);
jBtnMmsAlterar.setEnabled(false);
    }//GEN-LAST:event_jBtnMmsConfirmarActionPerformed

    private void jBtnMmsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsCancelarActionPerformed
        // TODO add your handling code here:
        jTxtMmsCategoria.setEnabled(true);
jTxtMmsCodigo.setEnabled(true);
jTxtMmsDescricao.setEnabled(true);
jTxtMmsFornecedor.setEnabled(true);
jTxtMmsIQuantidade.setEnabled(true);
jTxtMmsMarca.setEnabled(true);
jTxtMmsPreco.setEnabled(true);
jTxtMmsProduto.setEnabled(true);
jBtnMmsCancelar.setEnabled(true);
jBtnMmsConfirmar.setEnabled(true);
jBtnMmsIncluir.setEnabled(false);
jBtnMmsExcluir.setEnabled(false);
jBtnMmsPesquisar.setEnabled(false);
jBtnMmsAlterar.setEnabled(false);
    }//GEN-LAST:event_jBtnMmsCancelarActionPerformed

    private void jBtnMmsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsExcluirActionPerformed
        // TODO add your handling code here:
        jTxtMmsCategoria.setEnabled(false);
jTxtMmsCodigo.setEnabled(false);
jTxtMmsDescricao.setEnabled(false);
jTxtMmsFornecedor.setEnabled(false);
jTxtMmsIQuantidade.setEnabled(false);
jTxtMmsMarca.setEnabled(false);
jTxtMmsPreco.setEnabled(false);
jTxtMmsProduto.setEnabled(false);
jBtnMmsCancelar.setEnabled(false);
jBtnMmsConfirmar.setEnabled(false);
jBtnMmsIncluir.setEnabled(true);
jBtnMmsExcluir.setEnabled(true);
jBtnMmsPesquisar.setEnabled(true);
jBtnMmsAlterar.setEnabled(true);
    }//GEN-LAST:event_jBtnMmsExcluirActionPerformed

    private void jBtnMmsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsAlterarActionPerformed
        // TODO add your handling code here:
jTxtMmsCategoria.setEnabled(false);
jTxtMmsCodigo.setEnabled(false);
jTxtMmsDescricao.setEnabled(false);
jTxtMmsFornecedor.setEnabled(false);
jTxtMmsIQuantidade.setEnabled(false);
jTxtMmsMarca.setEnabled(false);
jTxtMmsPreco.setEnabled(false);
jTxtMmsProduto.setEnabled(false);
jBtnMmsCancelar.setEnabled(false);
jBtnMmsConfirmar.setEnabled(false);
jBtnMmsIncluir.setEnabled(true);
jBtnMmsExcluir.setEnabled(true);
jBtnMmsPesquisar.setEnabled(true);
jBtnMmsAlterar.setEnabled(true);
    }//GEN-LAST:event_jBtnMmsAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgMmsProduto dialog = new JDlgMmsProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMmsAlterar;
    private javax.swing.JButton jBtnMmsCancelar;
    private javax.swing.JButton jBtnMmsConfirmar;
    private javax.swing.JButton jBtnMmsExcluir;
    private javax.swing.JButton jBtnMmsIncluir;
    private javax.swing.JButton jBtnMmsPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtMmsCategoria;
    private javax.swing.JTextField jTxtMmsCodigo;
    private javax.swing.JTextField jTxtMmsDescricao;
    private javax.swing.JTextField jTxtMmsFornecedor;
    private javax.swing.JTextField jTxtMmsIQuantidade;
    private javax.swing.JTextField jTxtMmsMarca;
    private javax.swing.JTextField jTxtMmsPreco;
    private javax.swing.JTextField jTxtMmsProduto;
    // End of variables declaration//GEN-END:variables
}
