/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author lxn
 */
public class JDlgMmsEspecificacao extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgMmsEspecificacao.class.getName());

    /**
     * Creates new form JDlgMmsEspecificacao
     */
    public JDlgMmsEspecificacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          setTitle("Especificações do Produto");
        setLocationRelativeTo(null);
       jTxtMmsTipo.setEnabled(false);
       jTxtMmsCodigo.setEnabled(false);
       jTxtMmsGenero.setEnabled(false);
       jTxtMmsMarca.setEnabled(false);
       jTxtMmsMaterial.setEnabled(false);
       jTxtMmsTamanho.setEnabled(false);
       jTxtMmsTipoSolado.setEnabled(false);
       jBtnMmsCancelar.setEnabled(false);
       jBtnMmsConfirmar.setEnabled(false);
       jBtnMmsExcluir.setEnabled(true);
       jBtnMmsAlterar.setEnabled(true);
       jBtnMmsIncluir.setEnabled(true);
       jBtnMmsPesquisar.setEnabled(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnMmsExcluir = new javax.swing.JButton();
        jTxtMmsMaterial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtMmsTipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtMmsGenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBtnMmsIncluir = new javax.swing.JButton();
        jBtnMmsAlterar = new javax.swing.JButton();
        jTxtMmsTipoSolado = new javax.swing.JTextField();
        jBtnMmsConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtMmsMarca = new javax.swing.JTextField();
        jTxtMmsCodigo = new javax.swing.JTextField();
        jBtnMmsCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBtnMmsPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtMmsTamanho = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnMmsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/Excluir.png"))); // NOI18N
        jBtnMmsExcluir.setText("Excluir");
        jBtnMmsExcluir.addActionListener(this::jBtnMmsExcluirActionPerformed);

        jLabel5.setText("Tipo:");

        jLabel6.setText("Gênero:");

        jLabel7.setText("Tipo do Solado:");

        jBtnMmsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/incluir.png"))); // NOI18N
        jBtnMmsIncluir.setText("Incluir");
        jBtnMmsIncluir.addActionListener(this::jBtnMmsIncluirActionPerformed);

        jBtnMmsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/alterar.png"))); // NOI18N
        jBtnMmsAlterar.setText("Alterar");
        jBtnMmsAlterar.addActionListener(this::jBtnMmsAlterarActionPerformed);

        jBtnMmsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/confirmar.png"))); // NOI18N
        jBtnMmsConfirmar.setText("Confirmar");
        jBtnMmsConfirmar.addActionListener(this::jBtnMmsConfirmarActionPerformed);

        jLabel2.setText("Cor:");

        jBtnMmsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cancelar.png"))); // NOI18N
        jBtnMmsCancelar.setText("Cancelar");
        jBtnMmsCancelar.addActionListener(this::jBtnMmsCancelarActionPerformed);

        jLabel3.setText("Marca:");

        jBtnMmsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/pesquisar.png"))); // NOI18N
        jBtnMmsPesquisar.setText("Pesquisar");

        jLabel1.setText("Tamanho:");

        jLabel9.setText("Material:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtMmsTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtMmsGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtMmsTipoSolado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtMmsTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtMmsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxtMmsMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTxtMmsMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnMmsIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMmsAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMmsExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMmsConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnMmsCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnMmsPesquisar)
                .addGap(0, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMmsTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMmsGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMmsTipoSolado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMmsIncluir)
                    .addComponent(jBtnMmsAlterar)
                    .addComponent(jBtnMmsExcluir)
                    .addComponent(jBtnMmsConfirmar)
                    .addComponent(jBtnMmsCancelar)
                    .addComponent(jBtnMmsPesquisar))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMmsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsIncluirActionPerformed
        // TODO add your handling code here:
        jTxtMmsTipo.setEnabled(true);
jTxtMmsCodigo.setEnabled(true);
jTxtMmsGenero.setEnabled(true);
jTxtMmsMarca.setEnabled(true);
jTxtMmsMaterial.setEnabled(true);
jTxtMmsTamanho.setEnabled(true);
jTxtMmsTipoSolado.setEnabled(true);
jBtnMmsCancelar.setEnabled(true);
jBtnMmsConfirmar.setEnabled(true);
jBtnMmsExcluir.setEnabled(false);
jBtnMmsAlterar.setEnabled(false);
jBtnMmsIncluir.setEnabled(false);
jBtnMmsPesquisar.setEnabled(false);
    }//GEN-LAST:event_jBtnMmsIncluirActionPerformed

    private void jBtnMmsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsConfirmarActionPerformed
        // TODO add your handling code here:
        jTxtMmsTipo.setEnabled(true);
jTxtMmsCodigo.setEnabled(true);
jTxtMmsGenero.setEnabled(true);
jTxtMmsMarca.setEnabled(true);
jTxtMmsMaterial.setEnabled(true);
jTxtMmsTamanho.setEnabled(true);
jTxtMmsTipoSolado.setEnabled(true);
jBtnMmsCancelar.setEnabled(true);
jBtnMmsConfirmar.setEnabled(true);
jBtnMmsExcluir.setEnabled(false);
jBtnMmsAlterar.setEnabled(false);
jBtnMmsIncluir.setEnabled(false);
jBtnMmsPesquisar.setEnabled(false);
    }//GEN-LAST:event_jBtnMmsConfirmarActionPerformed

    private void jBtnMmsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsCancelarActionPerformed
        // TODO add your handling code here:
        jTxtMmsTipo.setEnabled(true);
jTxtMmsCodigo.setEnabled(true);
jTxtMmsGenero.setEnabled(true);
jTxtMmsMarca.setEnabled(true);
jTxtMmsMaterial.setEnabled(true);
jTxtMmsTamanho.setEnabled(true);
jTxtMmsTipoSolado.setEnabled(true);
jBtnMmsCancelar.setEnabled(true);
jBtnMmsConfirmar.setEnabled(true);
jBtnMmsExcluir.setEnabled(false);
jBtnMmsAlterar.setEnabled(false);
jBtnMmsIncluir.setEnabled(false);
jBtnMmsPesquisar.setEnabled(false);
    }//GEN-LAST:event_jBtnMmsCancelarActionPerformed

    private void jBtnMmsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsAlterarActionPerformed
        // TODO add your handling code here:
        jTxtMmsTipo.setEnabled(false);
jTxtMmsCodigo.setEnabled(false);
jTxtMmsGenero.setEnabled(false);
jTxtMmsMarca.setEnabled(false);
jTxtMmsMaterial.setEnabled(false);
jTxtMmsTamanho.setEnabled(false);
jTxtMmsTipoSolado.setEnabled(false);
jBtnMmsCancelar.setEnabled(false);
jBtnMmsConfirmar.setEnabled(false);
jBtnMmsExcluir.setEnabled(true);
jBtnMmsAlterar.setEnabled(true);
jBtnMmsIncluir.setEnabled(true);
jBtnMmsPesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtnMmsAlterarActionPerformed

    private void jBtnMmsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMmsExcluirActionPerformed
        // TODO add your handling code here:
        jTxtMmsTipo.setEnabled(false);
jTxtMmsCodigo.setEnabled(false);
jTxtMmsGenero.setEnabled(false);
jTxtMmsMarca.setEnabled(false);
jTxtMmsMaterial.setEnabled(false);
jTxtMmsTamanho.setEnabled(false);
jTxtMmsTipoSolado.setEnabled(false);
jBtnMmsCancelar.setEnabled(false);
jBtnMmsConfirmar.setEnabled(false);
jBtnMmsExcluir.setEnabled(true);
jBtnMmsAlterar.setEnabled(true);
jBtnMmsIncluir.setEnabled(true);
jBtnMmsPesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtnMmsExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgMmsEspecificacao dialog = new JDlgMmsEspecificacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMmsAlterar;
    private javax.swing.JButton jBtnMmsCancelar;
    private javax.swing.JButton jBtnMmsConfirmar;
    private javax.swing.JButton jBtnMmsExcluir;
    private javax.swing.JButton jBtnMmsIncluir;
    private javax.swing.JButton jBtnMmsPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtMmsCodigo;
    private javax.swing.JTextField jTxtMmsGenero;
    private javax.swing.JTextField jTxtMmsMarca;
    private javax.swing.JTextField jTxtMmsMaterial;
    private javax.swing.JTextField jTxtMmsTamanho;
    private javax.swing.JTextField jTxtMmsTipo;
    private javax.swing.JTextField jTxtMmsTipoSolado;
    // End of variables declaration//GEN-END:variables
}
